# Conda Environment Setup Instructions
#  - Using an environment.yml file with conda
#  - Key Terminal Commands:
#
#    conda env create -f environment.yml
#    conda env update --file environment.yml --prune
#    conda env export --name ai-agent-env > environment.yml
#    conda env remove --name ai-agent-env
#    conda env list

name: ai-agent-env
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.11.9
  - pip
  - bottleneck
  - pip:
      - fastapi==0.112.2
      - structlog==24.4.0
      - python-dotenv==1.0.1
      - uvicorn==0.30.6
      - langchain==0.3.0
      - langchain-community==0.3.0
      - langchain-openai==0.2.0
      - python-multipart==0.0.9
      - pypdf==5.0.0
      - faiss-cpu==1.7.3